---
title: "HTML_introducciónR"
author: "Karen Achote"
date: "26/2/2022"
output: html_document
---


## TAREA 1: TIPOS DE DATOS
```{r Ejercicio 1}
# Crear un identificador de nombre "ciudad" y asigne 
# como valor el nombre de alguna ciudad

ciudad <- "Orellana"
```

```{r Ejercicio 2}
# Crear un identificador de nombre "pais_andes" y asigne como valor 
# los nombres de los países por donde cruza la cordillera de Los Andes

paises_andes <- c("Venezuela", "Colombia", "Ecuador", "Perú", "Bolivia", "Chile")
```

```{r Ejercicio 3}

# Crear un dataframe con 12 eventos (files) y 5 variables (columnas), 
# cada columna debe tener diferentes tipos de datos (entero, decimal, 
# caracter, logico)

poblacion_paises_america <- data.frame(Identador =seq(1:12),
                                       norte_sur = as.factor(c(rep(0, 10), 1, 1)),
                                       paises = c("Venezuela", "Colombia", "Ecuador", "Perú", "Bolivia","Chile", "Brasil", "Argentina", "Paraguay", "Uruguay", "Canadá", "USA"),
                                       poblacion = c(28.43, 50.88, 17.64, 33.05, 11.67, 19.11, 212.55, 45.19, 7.1, 3.4, 35.36, 323.99)) #millones

``` 
```{r Ejercicio 4}                         

# Cargue el dataset "DNase" e identifique su estructura. Extraiga (subset) 
# los datos que cumplan con las condiciones de: 
#   1. "conc" (concentracion) entre 0.1 y 0.2
#   2. "Run" diferente a 2, "conc" mayor a 0.2 y "density" menor o igual a 1.0

database <- data(DNase)
class(DNase)
first_filter <- subset(DNase, conc < 0.2 & conc > 0.1)
second_filter <- subset(DNase, Run != 2 & conc > 0.2 & density <= 1)

```     


